import Welcome from "./Welcome";
import Login from "./Login";
import SignUp from "./SignUp";
import Forgot from "./Forgot";
import Settings from "./Settings";
import About from "./About";
import Home from "./Home";
import Map from "./Map";
import History from "./History";
// import HistoryStat from "./HistoryStat";
